# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-02 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopperManage', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_uploadtime',
            field=models.IntegerField(default=0),
        ),
    ]
