# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-04 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopperManage', '0004_product_sellerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_buyerid',
            field=models.IntegerField(default=0),
        ),
    ]
