# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-08 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopperManage', '0005_product_product_buyerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sellerid',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
    ]
