# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-27 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('account', models.CharField(max_length=50, unique=True)),
                ('sex', models.CharField(max_length=10)),
                ('prefer_clothes', models.CharField(max_length=50)),
                ('prefer_pants', models.CharField(max_length=50)),
                ('prefer_books', models.CharField(max_length=50)),
                ('prefer_foods', models.CharField(max_length=50)),
            ],
        ),
    ]
