# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-15 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopperProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default=0)),
                ('rest', models.IntegerField(default=0)),
                ('upgradetime', models.IntegerField(default=0)),
            ],
        ),
    ]
